**Percentage Calculator using advanced modules**


In [41]:
import numpy as np

**Creating a program to find percetage of 3 students at once**

In [46]:
emptyArray = np.empty((3,3))
for arrayindex in range(0,len(emptyArray)):
    for itemindex in range(0,len(emptyArray[arrayindex])):
        emptyArray[arrayindex,itemindex] = int(input(f'enter the marks of student {arrayindex+1} in subject {itemindex+1}:'))

In [47]:
print(emptyArray)
sumArray = emptyArray.sum(axis = 1)
for index in range(0,len(sumArray)):
    print(f"percentage of student {index+1} is {(sumArray[index]/240)*100}%")

[[56. 67. 78.]
 [80. 67. 67.]
 [78. 80. 56.]]
percentage of student 1 is 83.75%
percentage of student 2 is 89.16666666666667%
percentage of student 3 is 89.16666666666667%
